import requests
# TOKEN = 'pak.7OERYeSdRavJ28dreS94YdRMe~.qKPn5SwDA'
# accountId = 'd56da33f-91e8-470c-85ab-cba73c3f9427'
# HOST = 'https://stage.proautoma.com'

TOKEN = 'pak.rtJv6oUsG1g4WQZZJG6Ej~yd3GaJMrtT124C'
accountId = '4919ff10-3e42-4267-8db1-3573dfb3e155'
HOST = 'http://localhost:8080'

topUrls = ["facebook.com/",
           "twitter.com/",
           "google.com/",
           "youtube.com/",
           "instagram.com/",
           "linkedin.com/",
           "wordpress.org/",
           "pinterest.com/",
           "wikipedia.org/",
           "wordpress.com/",
           "blogspot.com/",
           "apple.com/",
           "adobe.com/",
           "tumblr.com/",
           "youtu.be/",
           "amazon.com/",
           "goo.gl/",
           "vimeo.com/",
           "flickr.com/",
           "microsoft.com/",
           "yahoo.com/",
           "godaddy.com/",
           "qq.com/",
           "bit.ly/",
           "vk.com/",
           "reddit.com/",
           "w3.org/",
           "baidu.com/",
           "nytimes.com/",
           "t.co/",
           "europa.eu/",
           "wp.com/",
           "statcounter.com/",
           "jimdo.com/",
           "blogger.com/",
           "github.com/",
           "weebly.com/",
           "soundcloud.com/",
           "mozilla.org/",
           "bbc.co.uk/",
           "myspace.com/",
           "google.de/",
           "addthis.com/",
           "nih.gov/",
           "theguardian.com/",
           "google.co.jp/",
           "cnn.com/",
           "stumbleupon.com/",
           "gravatar.com/",
           "digg.com/",
           "addtoany.com/",
           "creativecommons.org/",
           "paypal.com/",
           "yelp.com/",
           "imdb.com/",
           "huffingtonpost.com/",
           "feedburner.com/",
           "issuu.com/",
           "wixsite.com/",
           "wix.com/",
           "dropbox.com/",
           "forbes.com/",
           "google.co.uk/",
           "washingtonpost.com/",
           "bluehost.com/",
           "etsy.com/",
           "go.com/",
           "msn.com/",
           "ameblo.jp/",
           "archive.org/",
           "slideshare.net/",
           "e-recht24.de/",
           "weibo.com/",
           "fc2.com/",
           "eventbrite.com/",
           "parallels.com/",
           "doubleclick.net/",
           "sourceforge.net/",
           "amazon.co.uk/",
           "telegraph.co.uk/",
           "ebay.com/",
           "amzn.to/",
           "livejournal.com/",
           "51.la/",
           "free.fr/",
           "yahoo.co.jp/",
           "reuters.com/",
           "taobao.com/",
           "wikimedia.org/",
           "amazon.de/",
           "typepad.com/",
           "hatena.ne.jp/",
           "bloomberg.com/",
           "elegantthemes.com/",
           "usatoday.com/",
           "about.com/",
           "medium.com/",
           "macromedia.com/",
           "xing.com/",
           "bing.com/",
           "time.com/",
           "www.gov.uk/",
           "google.it/",
           "cdc.gov/",
           "tripadvisor.com/",
           "cpanel.net/",
           "amazon.co.jp/",
           "npr.org/",
           "harvard.edu/",
           "bbb.org/",
           "aol.com/",
           "constantcontact.com/",
           "latimes.com/",
           "list-manage.com/",
           "webs.com/",
           "opera.com/",
           "blogspot.co.uk/",
           "live.com/",
           "bandcamp.com/",
           "apache.org/",
           "bbc.com/",
           "businessinsider.com/",
           "cpanel.com/",
           "disqus.com/",
           "behance.net/",
           "mit.edu/",
           "rambler.ru/",
           "gnu.org/",
           "spotify.com/",
           "joomla.org/",
           "google.es/",
           "line.me/",
           "wired.com/",
           "github.io/",
           "stanford.edu/"
           ]

#url = HOST + '/api/monitors?offset=0&limit=10'
endpoint = HOST + '/api/monitors'
headers = {'Content-Type': 'application/json',
           'Authorization': 'Bearer {}'.format(TOKEN),
           'x-proautoma-accountid': accountId}


for url in topUrls:
    x = requests.put(endpoint, headers=headers, json={
        'method': 'GET',
        'name': url,
        'url': 'https://www.'+url,
        'frequency': '60',
        'locations': ['us-east1'],
        'body': ''
    })

    print(x)
    print(x.text)
